### PR TITLE
fix(universal-cookie): remove object-assign

### PR DESCRIPTION
**Pull request by chmelevskij**

### CODE REVIEW

**Comment by ericclemmons** [comment]
Can we re-run this build & get this released?

**Comment by chmelevskij** [comment]
@ericclemmons https://github.com/reactivestack/cookies/issues/262#issuecomment-690135354 solution is decent workaround for now

**Comment by eXon** [comment]
I'll release the fix tonight. Thanks for taking the time to do a PR!

**Comment by ericclemmons** [comment]
Thanks @eXon & @chmelevskij!

Let us know once it's published to NPM & we'll run some checks on our side as well 🙏

**Comment by eXon** [comment]
It's published on v4.0.4 (AKA require not found 😂). Let me know if it works!

**Pull request merged**
