### PR TITLE
add Typescript definitions for universal-cookie

### PR DESCRIPTION
**Pull request by jakemmarsh**

### CODE REVIEW

**Comment by tgriesser** [comment]
+1 would be great to see! @jakemmarsh if this doesn't get merged anytime soon would you mind adding it to DefinitelyTyped?

**Comment by jakemmarsh** [comment]
@tgriesser PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28017

**Comment by eXon** [comment]
It should be merged by next week. Sorry about the delay im out of town.

**Comment by lyzhovnik** [comment]
I am waiting for it too.

**Comment by eXon** [comment]
The library has been rewritten in TypeScript so this should not be necessary anymore. Thanks for the PRO tho!

**Pull request closed without merging**
